classDiagram
class PresentationLayer {
    <<Interface>>
    +ServiceAPI
    +ServiceUser
    +ServiceReview
    +ServicePlace
    +ServiceAmenity
}
class BusinessLogicLayer {
    +FacadeBL <<Facade>>
    +User
    +Place
    +Review, 
    +Amenity
}
class PersistenceLayer {
    +UserRepository
    +PlaceRepository
    +ReviewRepository
    +AmenityRepository
}
PresentationLayer --> BusinessLogicLayer : Facade Pattern
BusinessLogicLayer --> PersistenceLayer : Database Operations