classDiagram
class User {
    +UUID
    +lastName : string
    +firstName: string
    +password: string
    +created_ad
    +update_ad
}
class Place {
    +UUID
    +title
    +description
    +price
    +latitude
    +longitude
}
class Review {
    +UUID
    +place
    +user
    +rating
    +comment
}
class Amenity {
    +UUID
    +name
    +description
}
Place --|> User : Inheritance
Review o-- User : Composition
Review --> Place : Association
Place o-- Amenity : Composition